services:
  - type: web
    name: ncwu-api
    env: node
    region: oregon
    plan: free
    rootDir: server
    buildCommand: npm install && npx tsc; exit 0
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
        sync: false
      - key: JWT_SECRET
        generateValue: true
        sync: false
      - key: DATABASE_URL
        sync: false
    autoDeploy: true

  - type: web
    name: ncwu-frontend
    env: static
    region: oregon
    plan: free
    rootDir: app
    buildCommand: npm run build
    staticPublishPath: ./dist
    redirects:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://ncwu-api.onrender.com/api
        sync: false
      - key: VITE_FIREBASE_API_KEY
        value: AIzaSyCozP3dd1ceOVHgeQe9kBTB6MqsD9bcyrI
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        value: ncwu-community.firebaseapp.com
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        value: ncwu-community
        sync: false
      - key: VITE_FIREBASE_STORAGE_BUCKET
        value: ncwu-community.firebasestorage.app
        sync: false
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        value: "921961386134"
        sync: false
      - key: VITE_FIREBASE_APP_ID
        value: "1:921961386134:web:06aadb44ab47a647ffb2b7"
        sync: false
    autoDeploy: true
